apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 128Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /dev/mapper/data-grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - columbo
